# Generated by Django 4.1.4 on 2022-12-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feed", "0002_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="catagory",
            new_name="category",
        ),
    ]
